project 'MoviesSwiftProject.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MoviesSwiftProject' do
  
  use_frameworks!

  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'SDWebImage', '~> 4.0'
  pod 'Cosmos'
  pod 'iOSDropDown'
pod 'ReachabilitySwift'
end
